### ISSUE TITLE
True strain calculation for Compression sample is incorrect

### ISSUE THREAD

**Issue by markhalonen** [relinc/SPLibraries#8]

**Comment by markhalonen** [comment]
@bhalonen I began writing the tests. Perhaps you should finish writing them to double-check that this is indeed the correct calculation for true strain?

**Comment by markhalonen** [comment]
Prevents temptation of rubber-stamp approval

**Comment by markhalonen** [comment]
@bhalonen These new calculations depend on the fact that `displacement` is always positive, no matter if it's Tension or Compression. It appears that this is indeed true, but I would like to confirm by running a real sample. Unfortunately the relinc website only provides example Compression data. We should aquire sample tension data as well. Should be parallel with the Compression data on the site which has **all** information required to run SURE-Pulse, including bar setups and strain gauges.

**Comment by bhalonen** [comment]
I'll check my computer to see if I have samples there.

**Comment by bhalonen** [comment]
Looks good. You should make a pull request from a different fork as well so I can review your code.

**Comment by markhalonen** [comment]
I can make a PR without doing a fork. I'm working on `mgh-8`, which I can create a PR into `master`

**Comment by markhalonen** [comment]
I would like to do a gull GUI test with Tension data first. Need some tension data though, I cleared my cpu so I don't have any.

**Comment by bhalonen** [comment]
Ok. Let's have a PR before moving code into master.

**Comment by markhalonen** [comment]
I ran the Tension data and confirmed that the true strain results are the same as before changing the true strain calculations. The true strain calculations were correct for Tension.

Also confirmed that compression true strain is now higher than engineering strain, and confirmed that before this issue it was incorrectly lower than engineering strain.
